version: 2

sources:
  - name: raw 
    database: datoscat_tfm
    schema: raw
    tables:
    - name: patient
    - name: diagnoses
    - name: procedures
    - name: episodes
    - name: external_cause